name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Ensure we get the .yarn directory containing the Yarn Berry release
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        # Remove the cache option as Yarn Berry manages its own cache
    
    - name: Enable Corepack
      run: |
        corepack enable
        corepack prepare yarn@stable --activate
    
    - name: Install dependencies
      run: yarn install
      
    - name: Lint
      run: yarn lint
      
    - name: Test
      run: yarn test
      
    - name: Build
      run: yarn build
